# Generated by Django 5.2.6 on 2025-09-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField()),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('kilometraje', models.PositiveIntegerField(default=0)),
                ('soat_vencimiento', models.DateField()),
                ('tecnomecanica_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('alquilado', 'Alquilado'), ('mantenimiento', 'Mantenimiento'), ('inactivo', 'Inactivo')], default='disponible', max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
